routes/web.php
<?php

use App\carts;
Route::get('/', function () {
    return view('welcome');
});
Route::get('/contact', function () {
    return view('contact');
})->name('contact') ; 


Route::get('/about', function () {
    return view('about');
})->name('about') ;


  //  language change
  Route::get('change-language/{lang}' , function($lang){
    
    App::setLocale($lang);
    // if(App::isLocale('ar')){
    //     dd(App::getLocale());
    // }
    // \App::setLocale($lang);

    // dd(App::getLocale());
    // dump($lang ,session('locale') );

    session()->put('locale', $lang);

    if(session('locale') == 'ar'){

        $_SESSION['language'] = 'arabic' ;
    }else{
        $_SESSION['language'] = 'english' ;

    }
    return redirect()->back();

    
} ) ->name ('change-language') ;


Route::get('email', function () {

    $orderstatus = App\orderstatuses::find(38);
    $shipping = App\shippings::first();
    // , , 'shipping' => $shipping
    return view('emails.order_status' , ['msg' => 'Hello World' , 'order' => $orderstatus  ] );
})->name('email') ;


Route::get('/product', 'ProductsController@showProducts' )->name('product') ;

Route::get('/gallery', 'GalleriesController@showGalleryImages' )->name('gallery') ;

// Route::get('/product', function () {
//     return view('product');
// });
Route::get('/userlogin', function () {


    // dd(url()->previous());

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }
    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }

    return view('userlogin');

})->name('userlogin') ;
Route::get('/signup', function () {

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }

    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }

    return view('signup');
});


Route::get('reset/password','RegusersController@resetEmailPassword')->name('reset.password');
Route::post('send-reset-password-link','RegusersController@sentPasswordResetLink')->name('send-reset-password-link');

Route::post('save-new-password','RegusersController@sentNewPassword')->name('save-new-password');


Route::get('password/reset/{email}/token/{token}','RegusersController@resetPassword')->name('password.reset.token');


Route::get('edit-profile' , 'RegusersController@editProfile')->name('edit-profile');


if(!isset($_SESSION)) 
{ 
    session_start(); 
}
use App\shippings;
use App\contactuses;
use App\orderstatuses;
use Illuminate\Support\Facades\Route;
Route::get('/checkout', function () {

    if( isset($_SESSION["logged_in"])) {
        $id = $_SESSION["id"];
    }
    //$carts = carts::where(['cid', $id],['is_approved', '0']);
    // $carts = carts::all()->where('is_approved', '0')->where('cid', $id);

   

    // if( isset($_SESSION["logged_in"])) {
    // }
        
        $session_carts = carts::where('session' , session()->getId() )->where('is_approved' , 0) ->get();

        // dd($session_carts);

        if( isset($_SESSION['id']) && $session_carts->count() > 0){

            foreach($session_carts->where('cid' , null ) as $cart){
                $cart->cid =  $_SESSION['id'];
                $cart->save();
            }

            $carts = carts::where('cid' , $id )->where('is_approved' , 0) ->get();
            
        }elseif(isset($_SESSION['id']) && $session_carts->count() == 0){
            
            $carts = carts::where('cid' , $id )->where('is_approved' , 0) ->get();
        }
        else{
            $carts = $session_carts;
        }

        // dd($carts);

        $shippings = shippings::all();
        return view('checkout',compact('carts','shippings'));

    // else{
    //     return redirect()->back()->with('error' , 'You must login before checkout');    
    // }
    
    
})->name('checkout') ;
Auth::routes();

Route::get('/home', 'AbcController@index')->middleware('auth');
Route::get('/header', 'HeaderController@index')->name('header');
Route::get('/aside', 'AsideController@index')->name('aside');
Route::resource('homes','HomeController')->middleware('auth');
Route::resource('categories','CategoriesController')->middleware('auth');
Route::get('/manage-category', 'CategoriesController@approve')->name('category');
Route::resource('products','ProductsController')->middleware('auth');

Route::get('products/exports/{ids}','ProductsController@exportProducts')->name('products.exports');

Route::get('/manage-products', 'ProductsController@approve')->name('products');
Route::resource('aboutuses','AboutusesController')->middleware('auth');
Route::resource('contactuses','ContactusesController')->middleware('auth');
Route::resource('orders','OrdersController')->middleware('auth');
Route::resource('homepages','HomepagesController')->middleware('auth');
Route::resource('galleries','GalleriesController')->middleware('auth');
Route::resource('shippings','ShippingsController')->middleware('auth');

Route::resource('regusers','RegusersController');

Route::get('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;

Route::get('reguser/{user}/orders','RegusersController@viewOrders')->name('reguser-orders');


Route::get('filter-users' , 'RegusersController@filter' )->name('filter-users') ;
Route::get('/export-customers/{ids}', 'RegusersController@exportCustomers')->name('export-customers');

Route::resource('carts','CartsController');
Route::resource('productsections','ProductsectionsController')->middleware('auth');
Route::get('/user-login', 'RegusersController@login')->name('orders');
Route::get('/user-logout', 'RegusersController@logout')->name('orders');
Route::get('/contact-form', 'ContactFormController@store')->name('orders');

Route::get('/carts', 'CartsController@store')->name('carts');
Route::get('/update-cart-quantity', 'CartsController@updateCartQuantity')->name('update-cart-quantity');

Route::get('/update-cart-quantity-ajax/{cart_id}/{quantity}', 'CartsController@updateCartQuantityAjax')->name('update-cart-quantity-ajax');

Route::post('register-guest', 'RegusersController@guestSignupStore')->name('register-guest') ;

Route::get('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');

Route::post('sadad-payment', 'OrderstatusesController@SadadPayment')->name('sadad-payment');

Route::get('sadad-payment-success', 'OrderstatusesController@SadadPaymentSuccess')->name('sadad-payment-success');

Route::get('paymentsuccess', 'OrderstatusesController@payment_success');
Route::get('paymenterror', 'OrderstatusesController@payment_error');

Route::get('/delete-cart', 'CartsController@delete')->name('carts');
Route::resource('admins','AdminsController')->middleware('auth');

Route::get('/contact-form','ContactFormController@create');
Route::post('/contact-form','ContactFormController@store');
Route::post('/user-logout','RegusersController@logout');
Route::post('/user-login', 'RegusersController@login');
// Route::get('/product-category', 'ProductsController@show1')->name('products');
Route::get('/product-category', 'ProductsController@showCategoryProducts')->name('products');

Route::get('/gallery-images', 'GalleriesController@showGallery')->name('gallery-images');

Route::get('/order-history', 'OrdersController@showHistory')->name('order-history');
Route::get('/order-history/{order}/details', 'OrdersController@showOrderDetails')->name('order-history.details');

Route::resource('orderstatuses','OrderstatusesController')->middleware('auth');

Route::get('/export-orders/{ids}', 'OrderstatusesController@exportOrders')->name('export-orders');

Route::get('/export-orders-products/{ids}', 'OrderstatusesController@exportOrdersProducts')->name('export-orders-products');

Route::get('/export-order/{ids}', 'OrderstatusesController@exportOrder')->name('export-order');

Route::get('/order-filter', 'OrderstatusesController@search')->name('orderstatuses');

Route::get('/product-filter', 'OrderstatusesController@search1')->name('orderstatuses');
Route::resource('first','FirstController');



// dropzone images
Route::post('/images-save', 'GalleriesController@saveDropzoneImage')->name('images-save') ;
Route::get('/images-delete/{id}', 'GalleriesController@deleteDropzoneImage');


Route::get('index', function(){
    return view('layouts.main');
});



Route::get('email-test/{id}', function($id){

    $orderstatus  = orderstatuses::find($id);
    $customer = $orderstatus->customer;

    $data['msg'] = 'Dear '.$customer->full_name .'<br>Your Order Status is now';
    $data['order'] = $orderstatus;

    $contact_email = contactuses::latest()->first()->email ;

    
    // return view('emails.order_status' , ['order' => $orderstatus , 'msg' => $data['msg']] );
    if($contact_email){

        // $view = 'emails.text_email';
        $view = 'emails.order_status';
        \Mail::send($view, $data, function ($message) use ($contact_email,$customer) {
            $message->to( 'saadanjum047@gmail.com', $customer->full_name);
            $message->from( env('MAIL_FROM_ADDRESS') , 'vQuick');
            $message->subject('Order Status Confirmation');
        });
    }

    
    

});

app/products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class products extends Model
{
    protected $fillable = [
        'image', 'name','arabic_name', 'description' , 'description_ar','price','stock_available','category','is_approved' 
    ];



    public function getProperNameAttribute($value){

        if(session('locale') == 'ar'){
            return $this->arabic_name;
        }else{
            return $this->name;
        }
    }

    public function getProperDescriptionAttribute($value){

        if(session('locale') == 'ar'){
            return $this->description_ar;
        }else{
            return $this->description;
        }
    }


}

resources/views/layouts/old/checkout2.blade.php
@extends('layouts.main')



@section('title')
<title>Checkout</title>
@endsection


@section('styles')
    
<style>

  .counter1 {
    width:90px !important;
  }

  .btn-danger:focus {
    border: none;
    box-shadow: none;

  }
  .remove-cart-button{
    background-color: white;
    border: none;
    box-shadow: none;
  }
  .remove-cart-button:focus {
    border: none;
    box-shadow: none;
  }
  .checkout-list-p{
    line-height: 18px !important;
  }

  .swal-footer{
    display: block;
  }
  .swal-footer{
    text-align: center;
  }
  .swal-button--guest{
    background-color: #666666 !important;
    border: 1px solid #666666 !important;
  }
  
  .swal-button--login{
    color: #999999;
  }
  
 
  .swal-button--guest:focus {
    background-color: #666666 !important;
    border: 1px solid #666666 !important;
    box-shadow : none !important;
  }
  .swal-button--guest:hover {
    background-color: #666666 !important;
    border: 1px solid #666666 !important;
  }  

  .swal-button--guest:not([disabled]):hover {
    background-color: #666666 !important;
    border: 1px solid #666666 !important;

  }
  
  .swal-button--guest:not([disabled]):hover {
    background-color: #666666 !important;
    border: 1px solid #666666 !important;

  }
</style>
  @endsection

@section('content')
    

<?php
if(!isset($_SESSION)) 
{ 
    session_start(); 
}
if(isset($_SESSION["id"])){
  $id = $_SESSION["id"];
}
$price=0;
$z=0;
?>
<!-- Header -->

       <div class="container mt-5 badip">
      <div class="row no1">
        <div class="col-md-6">
          <h1 class="chch1 checkout-h1">{{__('Checkout')}}</h1>
        </div>
        <div class="col-md-6">
          <h2 class="text-right"><a class="chch2 checkout-h2" href="/product">{{__('Continue Shopping')}}</a></h2>
        </div>
      </div>
    </div>
    <div class="container mb-4 mt-3 badip">
      <div class="row no2">
        <div class="col-md-6">
          <p class="chcp1 checkout-main-row">{{__('Items')}}</p>
        </div>
        <div class="col-md-3">
          <p class="chcp1 checkout-main-row">{{__('Quantity')}}</p>
        </div>
        <div class="col-md-3">
          <p class="chcp1 checkout-main-row">{{__('Price')}}</p>
        </div>

      </div>
      {{--  @dd($carts)  --}}
      <hr class="no3" style="background-color: #d9d9d9;margin-top: -10px;" >
      @foreach ($carts as $cart)
      <div class="row">
        <div class="col-md-2">
          <img src="files/{{ $cart->image}}" style="height: 160px;width: 550px;" class="img-checkout py-2" alt="">
        </div>
        <div class="col-md-4 pt-5">
          <h2 class="chch2 checkout-list-h2 ">{{ $cart->product->proper_name}}</h2>
          <p class="chcp1 checkout-list-p " style="line-height: 18px !important" >{{  Str::limit($cart->product->proper_description,100) }}</p>
        </div>
        <div class="col-md-3 pt-5" >
          <div class='counter-checkout'>
            <!--<div class='decrease-counter' onclick='decreaseCount(event, this)'>-</div>-->
              {{--  <input type='text' value='{{ $cart->quantity }}'  >  --}}
              <div id="quantity-buttons" style="border:1px solid #d3aea6 ; border-radius: 5px; height: 36px; "
              <div class='counter1'  style="margin-top:1px;">
                <div id="down" class='down' onclick='decreaseCount(event, this ,  {{$cart->id }})'>-</div>
                <input type='text' value='{{ $cart->quantity }}' id="quantity" name="quantity" class="counter_1" value='1'  >
                <div class='up' id="up" onclick='increaseCount(event, this , {{$cart->id}} )'>+</div>
              </div>
              
            <!--<div class='decrease-counter' Onclick='increaseCount(event, this)'>+</div>-->
            </div>
          </div>
          <div class="col-md-2 " style="padding-top: 62px;">
            <h2 class="chch2 c-price cart-price-{{$cart->id}}" >QR {{ $cart->price}}</h2>
          </div>
          <div class="col-md-1">  
            <form id="cart-{{$cart->id}}" action="{{ route('carts.destroy',$cart->id) }}" method="POST">
              @csrf
              @method('DELETE')
              <a href="javascript:;" onclick=" $('#cart-{{$cart->id}}').submit(); " class="remove-cart-button"><i class="fa fa-close chchfa"></i></a>
            </form>
          </div>
        </div>
        <hr class ="no3" style="background-color: #d9d9d9;">
        <?php
        $cart_price=$cart->price;
        $price+= $cart_price;
        ?>
        @endforeach
      </div>
    </div>

<!-- MOBILE DESIGN -->

<div class="container chotip  mt-4">
  @foreach($carts as $cart)
	<div class="row no-gutters  margin-bottom-2 ">
		<div class="col-sm-5 col-5 checkout-mobile">
			<img src="/files/{{$cart->image}}" class="img-fluid"  alt="">
		</div>
		<div class="col-sm-7 col-7 px-2 py-4 mobile-checkout-container" >
			<h2 class="chch2 font-weight-bold checkout-list-h2">{{ $cart->product->proper_name}}</h2>
      <a href="#" onclick="delete_cart({{$cart->id}})" > <i class="fa fa-times-circle" aria-hidden="true" style="float: right;margin-top:-25px;color: #0000005c;"></i></a>
      
      <form id="delete-cart-{{$cart->id}}"   action="{{ route('carts.destroy',$cart->id) }}" method="POST">
        @csrf
        @method('DELETE')
      </form>
      
        <button type="submit"  class="btn-block btnchch py-3 checkout-btn uncfocused-item" id="placebutn">{{__('PLACE ORDER')}}</button>

			{{--  <i class="fa fa-ellipsis-v" aria-hidden="true" style="float: right;margin-top:-25px;color: #0000005c;"></i>  --}}
			<p class="chcp1" style="font-size: 12px;">{{ Str::limit($cart->product->proper_description , 200)}} </p>
			<h2 class="chch2 m-price "><strong class="cart-price-{{$cart->id}}" >QR {{$cart->price}}</strong></h2>

			<div class='counter mt-1'>
				<div class='decrease-counter'  onclick='decreaseCount(event, this , {{$cart->id}} )'>-</div>
				<input type='text' value='{{$cart->quantity}}' class="chotoo" >
				<div class='up' style="background-color: #dcdcdc;font-size: 20px;width: 30px;height: 30px;padding-top: 2px;padding-left: 9px !important;" onclick='increaseCount(event, this , {{$cart->id}})'>+</div>
			</div>
		</div>
  </div>
  @php
  $cart_price=$cart->price;
  $price+= $cart_price;

  @endphp
  <hr style="background-color: #d9d9d9;">
  @endforeach
	
  {{--  carts end here  --}}

</div>

  @if($carts->count() > 0)
  <div class="container px-4 mt-2">
    <div class="row mt-5">
      <div class="col-md-12">
        <h2 class="shiping-fee" >{{__('Shipping fee')}}</h2>
        <h2 id="ddddd" class="shiping-fee text-right">QR {{ $shippings->first()->fee}}</h2>
        
      </div>
      <div class="col-xs-12 col-12 col-sm-12 col-md-3 col-lg-3">
        <select class="form-control" name="payment_method" >
          <option disabled>{{__("Select Payment Option")}}</option>
          <option value="cash on delivery" >{{__('Cash On Delivery')}}</option>
          <option value="paypal" >{{__("PayPal")}}</option>
        </select>
      </div>
      
      @foreach ($shippings as $shipping)
      <div class="col-md-6 ">
        {{--  <h2 id="ddddd" class="shiping-fee text-right">QR {{ $shipping->fee}}</h2>  --}}
      </div>
      <?php $total_price = $shipping->fee + array_sum($carts->pluck('price')->toArray());?>
      @endforeach
    </div>
	  <hr class="no3" style="background-color: #d9d9d9;margin: 1rem 0;">
	<div class="row mv">
		<div class="col-md-6">
		  <h2 class="shiping-fee-s">{{__('Sub total')}}</h2>
		</div>
		<div class="col-md-6">
		  <h2 id="ddddd" class="shiping-fee-s text-right sub-total ">QR {{ array_sum($carts->pluck('price')->toArray()) }}</h2>
		</div>
	</div>
	<div class="row mt-4 ">
		<div class="col-md-6">
		  <h2 class="shiping-fee-m">{{__('Total')}}<span class="mobile-p-v total-amount">QR  <span class="total-amount"> {{$total_price}}</span></span></h2>
		</div>
		<div class="col-md-6">
		  <h2 id="dddddd" class=" text-right m-n-v " >QR <span class="total-amount">{{$total_price}} </span> </h2>
		</div>
    <div class="col-md-12 mt-4" >  
      <form method="get" action="/order-cart" class="place-order-form">
      <input type="hidden" name="total_price" class="total-amount" value="{{ $total_price }}" >
      <input type="hidden" name="id" value="{{ $id ?? session()->getId() }}" >
      <button @if(isset($_SESSION['id'])) type="submit" @else  type="button" onclick="ask_how_to_checkout()" @endif  class="btn-block btnchch py-3 checkout-btn uncfocused-item" id="placebutn">{{__('PLACE ORDER')}}</button>
      </form>
    </div>
	</div>
</div>
@else
<div class="container px-4 mt-2">
	<div class="row mt-5">
		<div class="col-md-6">
		  <h2 class="shiping-fee" >{{__('Shipping fee')}}</h2>
		</div>
		<div class="col-md-6 ">
		  <h2 id="ddddd" class="shiping-fee text-right">QR 0</h2>
		</div>
	</div>
	<hr class="no3" style="background-color: #d9d9d9;margin: 1rem 0;">
	<div class="row mv">
		<div class="col-md-6">
		  <h2 class="shiping-fee-s">{{__('Sub total')}}</h2>
		</div>
		<div class="col-md-6">
		  <h2 id="ddddd" class="shiping-fee-s text-right">QR 0</h2>
		</div>
	</div>
	<div class="row mt-4 ">
		<div class="col-md-6">
		  <h2 class="shiping-fee-m">{{__('Total')}}<span class="mobile-p-v">QR 0</span></h2>
		</div>
		<div class="col-md-6">
		  <h2 id="dddddd" class=" text-right m-n-v">QR 0</h2>
		</div>
    <div class="col-md-12 mt-4" >
      @if($carts->count() > 0)
      <button class="btn-block btnchch py-3 checkout-btn uncfocused-item" id="placebutn">{{__('PLACE ORDER')}}</button>
      @endif
      </form>
    </div>
	</div>
</div>
@endif

<!-- MOBILE DESIGN ENDS -->
<div class="col-md-12 mt-4">
        @if(isset($carts) && $carts->count() > 0)
        <form method="get" action="/order-cart" class="place-order-form">
          <input type="hidden" name="total_price" class="total-amount" value="{{ $total_price }}" required>
          <input type="hidden" name="id" value="{{ $id ?? session()->getId()}}" >
          <button type="submit" class="m-check-out-button uncfocused-item">{{__("PLACE ORDER")}}</button>
        </form>
        @endif
        </div>



@if(isset($carts) && $carts->count() > 0)

<form action="{{route('guest-signup')}}" id="guest-signup-form" method="GET" >
  <input type="hidden" class="total-amount" name="total_price" value="{{$total_price}}" />
</form>

@endif

@endsection


@section('scripts')
<script>

  function ask_how_to_checkout(){
  

    swal("{{__('How would you link to continue')}}", {
      buttons: {
      login: {
        text: "{{__('Login')}}",
        value: "login",
      },
      
      guest : {
        text: "{{__('Guest')}}",
        value: "guest",
      },
    },
  })
  .then((value) => {
    switch (value) {
   
      case "login":
        $('.place-order-form').submit();
        break;
        
      case "guest":
      $('#guest-signup-form').submit();
      break;
   
        default:
      }
    });
  }
  

  function delete_cart(id){
    console.log(id)
    document.getElementById("delete-cart-"+id).submit();    
  }


  function increaseCount(e, el , cart_id) {
    
    var input = el.previousElementSibling;
    var value = parseInt(input.value, 10);
    value = isNaN(value) ? 0 : value;
    
    //el.onclick = false;


    $.ajax({
      url: '{{url("/")}}/update-cart-quantity-ajax/'+ cart_id + '/' + (value + 1) ,
      success: function(res){

        $('.cart-price-'+cart_id ).html( 'QR ' + res.cart.price);
        $('.total-amount').html( res.total_amount);
        $('.total-amount').val( res.total_amount);
        $('.sub-total').html('QR ' +  res.sub_total);
        value++;
        input.value = value;
  

    }
    }).fail(function(errors){
      //swal(errors.responseJSON.message);

      if(errors.responseJSON.error_code == 1){

        swal({text: '{{__("Category restriction exceeded")}}' , timer:5000});
  
      }
      if(errors.responseJSON.error_code == 2){
  
        swal({ text: '{{__("This item stock is not enough")}}', timer:5000});
  
      }
  
    });
    
    //el.onclick = true;
    //$(el).on('click',increaseCount(event , this , cart_id)); 

  }
  function decreaseCount(e, el , cart_id) {
  var input = el.nextElementSibling;
  var value = parseInt(input.value, 10);
  if (value > 1) {
  value = isNaN(value) ? 0 : value;

  //el.onclick = false;


  $.ajax({
    url: '{{url("/")}}/update-cart-quantity-ajax/'+ cart_id + '/' + (value - 1) ,
    success: function(res){

      $('.cart-price-'+cart_id ).html( 'QR ' + res.cart.price);
      $('.total-amount').html( res.total_amount);
      $('.total-amount').val( res.total_amount);

      $('.sub-total').html('QR ' +  res.sub_total);

      value--;
      input.value = value;


  }
  }).fail(function(errors){

    if(errors.responseJSON.error_code == 1){

      swal({ text: '{{__("Category restriction exceeded")}}' , timer:5000 });

    }
    if(errors.responseJSON.error_code == 2){

      swal( { text: '{{__("This item stock is not enough")}}' , timer:5000 });

    }

  });

  }
  }
  </script>
  <script>
  function openNav(){
    document.getElementById("mySidenav").style.width="300px";
  }
  function closeNav(){
    document.getElementById("mySidenav").style.width="0px";
  }
</script>
<?php
  if(isset($_SESSION['message'])) 
  { 
    $login_message= $_SESSION['message'];?>
    <script>
        swal("{{ $login_message }}");
        setTimeout(() => {  window.location.href = "{{ url('/checkout') }}"; }, 1000);
    </script><?php
    unset($_SESSION['message']);
  }
?>
  </script>
@endsection

resources/views/layouts/old/home1.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection