routes/web.php
<?php

use App\carts;
Route::get('/', function () {
    return view('welcome');
});
Route::get('/contact', function () {
    return view('contact');
})->name('contact') ; 


Route::get('/about', function () {
    return view('about');
})->name('about') ;


  //  language change
  Route::get('change-language/{lang}' , function($lang){
    
    App::setLocale($lang);
    // if(App::isLocale('ar')){
    //     dd(App::getLocale());
    // }
    // \App::setLocale($lang);

    // dd(App::getLocale());
    // dump($lang ,session('locale') );

    session()->put('locale', $lang);

    if(session('locale') == 'ar'){

        $_SESSION['language'] = 'arabic' ;
    }else{
        $_SESSION['language'] = 'english' ;

    }
    return redirect()->back();

    
} ) ->name ('change-language') ;


Route::get('email', function () {

    $orderstatus = App\orderstatuses::find(38);
    $shipping = App\shippings::first();
    // , , 'shipping' => $shipping
    return view('emails.order_status' , ['msg' => 'Hello World' , 'order' => $orderstatus  ] );
})->name('email') ;


Route::get('/product', 'ProductsController@showProducts' )->name('product') ;

Route::get('/gallery', 'GalleriesController@showGalleryImages' )->name('gallery') ;

// Route::get('/product', function () {
//     return view('product');
// });
Route::get('/userlogin', function () {


    // dd(url()->previous());

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }
    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }

    return view('userlogin');

})->name('userlogin') ;
Route::get('/signup', function () {

    if(isset($_SESSION['logged_in'])){
        return redirect()->back()->with('error' , 'Already Logged in');
    }

    if(strpos( url()->previous() ,  'checkout') ){
        session()->put('checkout' , 'checkout');
    }

    return view('signup');
});


Route::get('reset/password','RegusersController@resetEmailPassword')->name('reset.password');
Route::post('send-reset-password-link','RegusersController@sentPasswordResetLink')->name('send-reset-password-link');

Route::post('save-new-password','RegusersController@sentNewPassword')->name('save-new-password');


Route::get('password/reset/{email}/token/{token}','RegusersController@resetPassword')->name('password.reset.token');


Route::get('edit-profile' , 'RegusersController@editProfile')->name('edit-profile');


if(!isset($_SESSION)) 
{ 
    session_start(); 
}
use App\shippings;
use App\contactuses;
use App\orderstatuses;
use Illuminate\Support\Facades\Route;
Route::get('/checkout', function () {

    if( isset($_SESSION["logged_in"])) {
        $id = $_SESSION["id"];
    }
    //$carts = carts::where(['cid', $id],['is_approved', '0']);
    // $carts = carts::all()->where('is_approved', '0')->where('cid', $id);

   

    // if( isset($_SESSION["logged_in"])) {
    // }
        
        $session_carts = carts::where('session' , session()->getId() )->where('is_approved' , 0) ->get();

        // dd($session_carts);

        if( isset($_SESSION['id']) && $session_carts->count() > 0){

            foreach($session_carts->where('cid' , null ) as $cart){
                $cart->cid =  $_SESSION['id'];
                $cart->save();
            }

            $carts = carts::where('cid' , $id )->where('is_approved' , 0) ->get();
            
        }elseif(isset($_SESSION['id']) && $session_carts->count() == 0){
            
            $carts = carts::where('cid' , $id )->where('is_approved' , 0) ->get();
        }
        else{
            $carts = $session_carts;
        }

        // dd($carts);

        $shippings = shippings::all();
        return view('checkout',compact('carts','shippings'));

    // else{
    //     return redirect()->back()->with('error' , 'You must login before checkout');    
    // }
    
    
})->name('checkout') ;
Auth::routes();

Route::get('/home', 'AbcController@index')->middleware('auth');
Route::get('/header', 'HeaderController@index')->name('header');
Route::get('/aside', 'AsideController@index')->name('aside');
Route::resource('homes','HomeController')->middleware('auth');
Route::resource('categories','CategoriesController')->middleware('auth');
Route::get('/manage-category', 'CategoriesController@approve')->name('category');
Route::resource('products','ProductsController')->middleware('auth');

Route::get('products/exports/{ids}','ProductsController@exportProducts')->name('products.exports');

Route::get('/manage-products', 'ProductsController@approve')->name('products');
Route::resource('aboutuses','AboutusesController')->middleware('auth');
Route::resource('contactuses','ContactusesController')->middleware('auth');
Route::resource('orders','OrdersController')->middleware('auth');
Route::resource('homepages','HomepagesController')->middleware('auth');
Route::resource('galleries','GalleriesController')->middleware('auth');
Route::resource('shippings','ShippingsController')->middleware('auth');

Route::resource('regusers','RegusersController');

Route::get('guest-signup' ,'RegusersController@guestSignup' )->name('guest-signup') ;

Route::get('reguser/{user}/orders','RegusersController@viewOrders')->name('reguser-orders');


Route::get('filter-users' , 'RegusersController@filter' )->name('filter-users') ;
Route::get('/export-customers/{ids}', 'RegusersController@exportCustomers')->name('export-customers');

Route::resource('carts','CartsController');
Route::resource('productsections','ProductsectionsController')->middleware('auth');
Route::get('/user-login', 'RegusersController@login')->name('orders');
Route::get('/user-logout', 'RegusersController@logout')->name('orders');
Route::get('/contact-form', 'ContactFormController@store')->name('orders');

Route::get('/carts', 'CartsController@store')->name('carts');
Route::get('/update-cart-quantity', 'CartsController@updateCartQuantity')->name('update-cart-quantity');

Route::get('/update-cart-quantity-ajax/{cart_id}/{quantity}', 'CartsController@updateCartQuantityAjax')->name('update-cart-quantity-ajax');

Route::post('register-guest', 'RegusersController@guestSignupStore')->name('register-guest') ;

Route::get('/order-cart', 'OrderstatusesController@store')->name('orderstatuses');

Route::post('sadad-payment', 'OrderstatusesController@SadadPayment')->name('sadad-payment');

Route::get('sadad-payment-success', 'OrderstatusesController@SadadPaymentSuccess')->name('sadad-payment-success');

Route::get('paymentsuccess', 'OrderstatusesController@payment_success');
Route::get('paymenterror', 'OrderstatusesController@payment_error');

Route::get('/delete-cart', 'CartsController@delete')->name('carts');
Route::resource('admins','AdminsController')->middleware('auth');

Route::get('/contact-form','ContactFormController@create');
Route::post('/contact-form','ContactFormController@store');
Route::post('/user-logout','RegusersController@logout');
Route::post('/user-login', 'RegusersController@login');
// Route::get('/product-category', 'ProductsController@show1')->name('products');
Route::get('/product-category', 'ProductsController@showCategoryProducts')->name('products');

Route::get('/gallery-images', 'GalleriesController@showGallery')->name('gallery-images');

Route::get('/order-history', 'OrdersController@showHistory')->name('order-history');
Route::get('/order-history/{order}/details', 'OrdersController@showOrderDetails')->name('order-history.details');

Route::resource('orderstatuses','OrderstatusesController')->middleware('auth');

Route::get('/export-orders/{ids}', 'OrderstatusesController@exportOrders')->name('export-orders');

Route::get('/export-orders-products/{ids}', 'OrderstatusesController@exportOrdersProducts')->name('export-orders-products');

Route::get('/export-order/{ids}', 'OrderstatusesController@exportOrder')->name('export-order');

Route::get('/order-filter', 'OrderstatusesController@search')->name('orderstatuses');

Route::get('/product-filter', 'OrderstatusesController@search1')->name('orderstatuses');
Route::resource('first','FirstController');



// dropzone images
Route::post('/images-save', 'GalleriesController@saveDropzoneImage')->name('images-save') ;
Route::get('/images-delete/{id}', 'GalleriesController@deleteDropzoneImage');


Route::get('index', function(){
    return view('layouts.main');
});



Route::get('email-test/{id}', function($id){

    $orderstatus  = orderstatuses::find($id);
    $customer = $orderstatus->customer;

    $data['msg'] = 'Dear '.$customer->full_name .'<br>Your Order Status is now';
    $data['order'] = $orderstatus;

    $contact_email = contactuses::latest()->first()->email ;

    
    // return view('emails.order_status' , ['order' => $orderstatus , 'msg' => $data['msg']] );
    if($contact_email){

        // $view = 'emails.text_email';
        $view = 'emails.order_status';
        \Mail::send($view, $data, function ($message) use ($contact_email,$customer) {
            $message->to( 'saadanjum047@gmail.com', $customer->full_name);
            $message->from( env('MAIL_FROM_ADDRESS') , 'vQuick');
            $message->subject('Order Status Confirmation');
        });
    }

    
    

});

app/regusers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class regusers extends Model
{
    protected $fillable = [
        'email','password','full_name','phone','address','zone','street','building' , 'is_guest'
    ];


    public function orders(){
        return $this->hasMany(orderstatuses::class , 'cid');
    }
}

resources/views/regusers/create.blade.php
@extends('regusers.layout')
@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Add New Customer</h2>
      </div>
      <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('regusers.index') }}"> Back</a>
      </div>
    </div>
  </div>
      
  @if ($errors->any())
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  

  <form action="{{ route('regusers.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    
    <div class="row" style="width:80%;margin:auto;">   

      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Email:</strong>
          <input type="text" class="form-control" name="email" placeholder="Enter Email" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Password:</strong>
          <input type="password" class="form-control" placeholder="Enter Password" name="password" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Name:</strong>
          <input type="text" class="form-control" name="full_name" placeholder="Enter Name" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Mobile:</strong>
          <input type="text" class="form-control" name="phone" placeholder="Enter Mobile" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12" >
        <div class="form-group">
          <strong>Address:</strong>
          <input type="text" class="form-control" name="address" placeholder="Enter Address" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Zone:</strong>
          <input type="text" class="form-control" placeholder="Enter Zone No" name="zone" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Street:</strong>
          <input type="text" class="form-control" placeholder="Enter Street No" name="street" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Bilding:</strong>
          <input type="text" class="form-control" name="building" placeholder="Enter Building No" required="required"/>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>    
  </form>
  @endsection

resources/views/regusers/edit.blade.php
@extends('regusers.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Customer</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('regusers.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('regusers.update', $reguser->id) }}" method="POST">
        @csrf
        @method('PUT')
   
        <div class="row" style="width:80%;margin:auto;">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Email:</strong>
              <input type="text" class="form-control" name="email" value="{{ $reguser->email }}" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Password:</strong>
              <input type="password" class="form-control" value="{{ $reguser->password }}" name="password" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12" >
            <div class="form-group">
              <strong>Name:</strong>
              <input type="text" class="form-control" name="full_name" value="{{ $reguser->full_name }}" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12" >
            <div class="form-group">
              <strong>Mobile:</strong>
              <input type="text" class="form-control" name="phone" value="{{ $reguser->phone }}" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12" >
            <div class="form-group">
              <strong>Address:</strong>
              <input type="text" class="form-control" name="address" value="{{ $reguser->address }}" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Zone:</strong>
              <input type="text" class="form-control" value="{{ $reguser->zone }}" name="zone" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Street:</strong>
              <input type="text" class="form-control" value="{{ $reguser->street }}" name="street" required="required"/>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Bilding:</strong>
              <input type="text" class="form-control" name="building" value="{{ $reguser->building }}" required="required"/>
            </div>
          </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/regusers/index.blade.php
@extends('regusers.layout') 

@section('content')

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<form action="{{route('filter-users')}}" method="GET">

  <div class="col-12" style="display:grid;grid-template-columns:25% 25% 25% 20%;grid-column-gap:3%;">
      <div class="form-group mt-2">
        <input type="text" class="form-control" name="name" placeholder="Name"  @if(isset($filters) && isset($filters['name']) ) value="{{$filters['name']}}" @endif />
      </div>
      <div class="form-group mt-2">
        <input type="text" name="phone" class="form-control" placeholder="Phone" @if(isset($filters) && isset($filters['phone']) ) value="{{$filters['phone']}}" @endif  />
      </div>
      
      <div class="form-group mt-2">
        <input type="email" name="email" class="form-control" placeholder="Email" @if(isset($filters) && isset($filters['email']) ) value="{{$filters['email']}}" @endif  />
      </div>
      
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Search</button>
        <a class="btn btn-danger" href="{{route('regusers.index')}}">X Clear</a>
      </div>
      <div class="form-group">
      </div>
    </div>
  </form>

  @php
    if(isset($filtered_regusers)){
      $regusers = $filtered_regusers;
    }
@endphp

<div class="row">
        <div class="col-lg-12 margin-tb mb-3">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('export-customers' , json_encode ( $regusers->pluck('id')->toArray()) ) }}"> Export</a>
                <a class="btn btn-success ml-2" href="{{ route('regusers.create') }}"> Create New Customer</a>
            </div>
        </div>
      
       
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bregusered">
        <tr>
          <th>No</th>
          <th>Name</th>
          <th>Email</th>
          <th>Mobile Number</th>
          <th>Address</th>
          <th>Zone</th>
          <th>Street</th>
          <th>Building</th>
          <th width="280px">Action</th>
        </tr>
        @foreach ($regusers as $k => $reguser)
        <tr>
          <td>{{ $k+1 }}</td>
          <td>{{ $reguser->full_name }}</td>
          <td> {{ $reguser->email }} </td>
          <td>{{ $reguser->phone }}</td>
          <td>{{ $reguser->address }}</td>
          <td>{{ $reguser->zone }}</td>
          <td>{{ $reguser->street }}</td>
          <td>{{ $reguser->building }}</td>
          <td>
            <a href="javascript:;"onclick="ask_delete({{$reguser->id}})" class="text-danger "> <i class="fa fa-trash fa-lg"></i> </a>

            <a href="{{ route('regusers.edit',$reguser->id) }}" class=""> <i class="fa fa-edit fa-lg"></i> </a>

            <form style="display: inline" id="delete-form-{{$reguser->id}}" action="{{ route('regusers.destroy',$reguser->id) }}" method="POST">
              <a class="btn btn-info btn-sm" href="{{ route('regusers.show',$reguser->id) }}">Show</a>
              {{-- <a class="btn btn-primary" href="{{ route('regusers.edit',$reguser->id) }}">Edit</a> --}}
              @csrf
              @method('DELETE')
              {{--  <button type="submit" class="btn btn-danger">Delete</button>  --}}

            </form>
            <a href="{{route('reguser-orders' , $reguser->id )}}"  class="btn btn-success btn-sm">Orders </a>



          </td>
        </tr>
        @endforeach
    </table>

</div>




<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

    @if(
      $regusers instanceof \Illuminate\Pagination\Paginator ||
      $regusers instanceof Illuminate\Pagination\LengthAwarePaginator
    )
  
      {{$regusers->links() ?? ''}}
  @endif
  

 
      
@endsection

resources/views/regusers/layout.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>VQuick | Dashboard</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{asset('css/app.css')}}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    @include('/header');
    @include('/aside');
    <div class="content-wrapper">
        <section class="content-header">
            <h1 style="float:left;">
                Customers
            </h1>
        </section>
        <div style="padding:5%;">
            @yield('content')
        </div>
    </div>
    <footer class="main-footer">
        <strong>Copyright &copy; 2020 <a href="#">vQuick</a>.</strong> All rights reserved.
    </footer>
</div>
<script src="{{asset('js/app.js')}}"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<script>
    function ask_delete(id){
        
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
          }).then((result) => {
            if (result.value) {
                $('#delete-form-'+id).submit();
            }
          });   
    }

</script>



</body>
</html>

resources/views/regusers/show.blade.php
@extends('regusers.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Customer Details</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('regusers.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $reguser->email }}<br>
                <strong>Full Name:</strong>
                {{ $reguser->full_name }}<br>
                <strong>Mobile Number:</strong>
                {{ $reguser->phone }}<br>
                <strong>Address:</strong>
                {{ $reguser->address }}<br>
                <strong>Zone No.:</strong>
                {{ $reguser->zone }}<br>
                <strong>Street No.:</strong>
                {{ $reguser->street }}<br>
                <strong>Building No.:</strong>
                {{ $reguser->building }}
            </div>
        </div>
    </div>
@endsection

resources/views/regusers/user_orders.blade.php
@extends('orderstatuses.layout') 
@section('content')


<style>
  .badge-danger{
    background-color: red;
    color:white;
  }
  .badge-success{

  }
  .badge-primary{

  }
  .badge-warning{

  }
</style>


    <?php use App\regusers;?>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    
    <table class="table table-bordered">
        <tr>
          <th>Order Number</th>
          <th>Total Price</th>
          <th>Payment Status</th>
          <th>Status</th>
          <th>Customer Name</th>
          <th>Address</th>
          <th>Date Time</th>
          <th width="280px">Action</th>
        </tr>
        @foreach ($customer->orders->sortByDesc('id') as $orderstatus)
        <tr>
          <td>{{ $orderstatus->id }}</td>
          <td>{{ $orderstatus->total_price }}</td>
          <td>{{ $orderstatus->payment_method }}</td>
          <td>
            @if($orderstatus->status == 'pending')
            <span class="label label-danger">Pending</span>
            
            @elseif($orderstatus->status == 'confirmed')

            <span class="label label-primary">Confirmed</span>
            
            @elseif($orderstatus->status == 'out of delivery')
            
            <span class="label label-warning">Out Of Delivery</span>
            
            @elseif($orderstatus->status == 'delivered')
            
            <span class="label label-success">Delivered</span>

            @elseif($orderstatus->status == 'cancelled')
            
            <span class="label label-danger">Cancelled</span>
            
            @endif
          
          </td>
          <?php $cid=$orderstatus->cid;
          $regusers = regusers::all()->where('id',$cid); ?>
          @foreach ($regusers as $reguser)
          <?php $cname=$reguser->full_name;
          $caddress=$reguser->address;
          $czone=$reguser->zone;
          $cstreet=$reguser->street;
          $cbuilding=$reguser->building;
          $cdate=$reguser->created_at; ?>
          @endforeach
          <td>{{ $cname }}</td>
          <td>Building: {{ $cbuilding }}, Street: {{ $cstreet }}, Zone: {{ $czone }}, {{ $caddress }} </td>
          <td>{{ $orderstatus->created_at }}</td>
          <td>
            <form id="delete-form-{{$orderstatus->id}}" action="{{ route('orderstatuses.destroy',$orderstatus->id) }}" method="POST">
              <a class="btn btn-info" href="{{ route('orderstatuses.show',$orderstatus->id) }}">View</a>
              <a class="btn btn-primary" href="{{ route('orderstatuses.edit',$orderstatus->id) }}">Edit</a>
              @csrf
              @method('DELETE')
              {{--  <button type="submit" class="btn btn-danger">Delete</button>  --}}
              <button type="button" onclick="ask_delete({{$orderstatus->id}})" class="btn btn-danger">Delete</button>

            </form>
          </td>
        </tr>
        @endforeach
    </table>

  

@endsection